### ISSUE TITLE
Cờ tướng - Là user, tôi muốn chơi game cờ thế

### ISSUE THREAD

**Issue by CuongDo83** [TRI-HELP/TRIhelp#16]
**Definition of Done**
- Luật chơi và UI Flow như mô tả trong doc. 
**Tasks**
- [ ] Design - Document rule và UI Flow.
- [ ] Dev - Add temporay chess assets. 
- [ ] Dev - Add firebase SDK. 
- [ ] Dev - Create Firebase Project. Register Firebase app on FirebaseProject. 
- [ ] Dev - Check valid moment for Chess unit. 
- [ ] Dev - Prototype of simple movement for Chess unit. 
- [ ] Dev - Import ultilitie code. 
- [ ] Dev - Create chess unit data. 
- [ ] Dev - Create chessboard data.
